# Use root/example as user/password credentials
#version: '3.1'
services:
 www:
  image: php:apache
  volumes:
   - "./:/var/www/html" # sync project dir with container web dir
  ports:
   - 80:80
   - 443:443 # for future ssl trafic
 db:
  image: mysql:latest
  environment:
   - MYSQL_DATABASE=myapp
   - MYSQL_USER=admin
   - MYSQL_PASSWORD=
   - MYSQL_ALLOW_EMPTY_PASSWORD=1
  volumes:
   - "./db/sql/:/docker-entrypoint-initdb.d" #sync persistent sql with container
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - 8001:80
  environment:
   - PMA_HOST=db
   - PMA_PORT=3306